---
- name: Install repository prerequisites
  become: yes
  dnf:
    name:
      - fedora-workstation-repositories
      - dnf-plugins-core
    state: installed
  retries: 5
  delay: 2
  register: fedora_repository_installation
  until: fedora_repository_installation is succeeded

- name: Check if we need to install third-party repositories
  become: yes
  changed_when: no
  shell: |
    set -o pipefail
    dnf config-manager --dump {{ item }} | sed -n -e 's/enabled = //p'
  register: third_party_repos
  with_items: "{{ fedora_workstation_repos }}"
  args:
    warn: false

- name: Install official third-party repositories
  become: yes
  command: "dnf config-manager --set-enabled {{ item.item }}"
  with_items: "{{ third_party_repos.results }}"
  when: item.stdout == '0'
  args:
    warn: false

- name: Install Packages
  become: yes
  dnf:
    name: "{{ fedora_workstation_packages + fedora_toolbox_packages }}"
    state: present
  retries: 5
  delay: 2
  register: fedora_workstation_packages_installation
  until: fedora_workstation_packages_installation is succeeded

- name: Add the flathub flatpak repository remote to the system installation
  become: yes
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpaks from flathub
  become: yes
  flatpak:
    name: "{{ item }}"
    remote: flathub
  with_items: "{{ fedora_flatpaks }}"
