---
- name: Install Packages
  become: yes
  dnf:
    name: "{{ fedora_toolbox_packages }}"
    state: present
  retries: 5
  delay: 2
  register: fedora_toolbox_packages_installation
  until: fedora_toolbox_packages_installation is succeeded

- name: Install podman-compose
  become: yes
  pip:
    name: podman-compose
    executable: pip3
    extra_args: '--user'
