---
# tasks/setup-RedHat.yml
- name: Install Packages
  become: yes
  yum:
    name: "{{ fedora_common_packages }}"
    state: present
  retries: 5
  delay: 2
  register: redhat_packages
  until: redhat_packages is succeeded

- include_tasks: fedora-workstation.yml
  when: fedora_edition == 'workstation'

- include_tasks: fedora-server.yml
  when: fedora_edition == 'server'
